### PR TITLE
Support PHP 8

### PR DESCRIPTION
**Pull request by XedinUnknown**
- Discontinue PHP < 7.1.
- Support PHP 8.

### CODE REVIEW

**Comment by mecha** [comment]
Why does the package now have a minimum requirement of PHP 7.2?

**Comment by XedinUnknown** [comment]
Because to support PHP 8, I need to drop old versions, and PHP 7.2 sounds like a good start that's not too far ahead. Any reason not to do that?

**Comment by mecha** [comment]
Not any objective reason, just a personal one - I need this package on PHP 7.1

**Comment by XedinUnknown** [comment]
I think I can do that 👍

**Comment by XedinUnknown** [comment]
Done, @mecha 👍

**Comment by mecha** [comment]
Amazing! I'll review in a couple hours.

**Comment by XedinUnknown** [comment]
Cool! As a note: the original doc of `resolveKeys()` said that the keys will be preserved in the result. But this is not how it was used: it relied on a list, rather than a list/map hybrid. So I made a method that actually returns an ordered hybrid, and then converted it into a list. Because the originally declared functionality sounded useful anyway.

**Comment by mecha** [comment]
Yeah I might have removed the original functionality because it was unused, or I changed how it worked. And as always, I forget to update the doc.

**Review by mecha — DISMISSED** [review]
LGTM - just don't immediately create a release. The `@since` PHPdoc tags aren't up-to-date.

**Comment by XedinUnknown** [comment]
I'm thinking: screw those tags 😁

**Pull request merged**
